### ISSUE TITLE
[Feature Request] Option to enable right-click at 1 durability.

### ISSUE THREAD

**Issue by gomhaille** [sten-code/Breakable#1]
Pretty much the title, lol.

I wanted to know if this could be added, because I exclusively play survival with the "mcMMO" plugin: https://github.com/mcMMO-Dev/mcMMO

One of the features of this plugin is that you can right-click on a placed iron block to repair equipment, assuming you have the relevant resources within your inventory. When I use your mod *(Breakable)* in tandem with mcMMO, your mod blocks the repair function of mcMMO. 

So, I figure that having a configuration option to enable the use of right-click would be a workaround. *(Potentially even just enabling it for iron blocks specifically, but a general option is fine if that's too much.)*

**Comment by sten-code** [comment]
I am currently working on only blocking actions that damage the item you're holding, at the moment you can't right click with a pickaxe at 1 durability. With this, it will only block if you try to mine with it. I assume this feature would also solve your issue. 

I might also make an overwrite or toggle keybind.

**Comment by gomhaille** [comment]
Yup, it sounds like what you described would perfectly resolve my issue. Thank you for replying, and I'm looking forwards to that.

**Comment by sten-code** [comment]
I have just pushed the update and uploaded it to Modrinth. Could you please check if this has fixed your issue? There are probably a lot of bugs still, so please let me know if you find any.

Thank you for your suggestion.

**Comment by gomhaille** [comment]
So far, the mod seems to be working perfectly on my end. It lets me repair tools via mcMMO like I wanted, and it correctly stops me from causing any damage to tools.

I haven't encountered any bugs yet, but if I do, I'll be sure to open an issue. And, thank you for adding this.
